apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend-deployment.yaml
- backend-service.yaml
- celery-deployment.yaml
- kafka-statefulset.yaml
- postgres-statefulset.yaml
- redis-statefulset.yaml
- nginx-ingress.yaml
configMapGenerator:
- name: backend-config
  files:
  - ../config/backend-config.yaml